/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nacho
 */
public class KitchenView extends javax.swing.JFrame {

    /**
     * Creates new form KitchenView
     */
    public KitchenView() {
        initComponents();
        setSize(726, 652);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ShowButton = new javax.swing.JButton();
        ReadyButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderJTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 140, 0));
        jPanel4.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kitchen");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(270, 20, 140, 63);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 710, 80);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cliente :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 100, 430, 63);

        ShowButton.setBackground(new java.awt.Color(255, 140, 0));
        ShowButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        ShowButton.setForeground(new java.awt.Color(255, 255, 255));
        ShowButton.setText("Show Order");
        jPanel3.add(ShowButton);
        ShowButton.setBounds(500, 160, 180, 60);

        ReadyButton.setBackground(new java.awt.Color(255, 140, 0));
        ReadyButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        ReadyButton.setForeground(new java.awt.Color(255, 255, 255));
        ReadyButton.setText("Ready");
        jPanel3.add(ReadyButton);
        ReadyButton.setBounds(10, 160, 180, 60);

        jComboBox1.setBackground(new java.awt.Color(255, 140, 0));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(495, 96, 190, 50);

        OrderJTextPane.setBackground(new java.awt.Color(255, 255, 255));
        OrderJTextPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        OrderJTextPane.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        OrderJTextPane.setForeground(new java.awt.Color(0, 0, 0));
        OrderJTextPane.setText("Select an order to view...");
        jScrollPane1.setViewportView(OrderJTextPane);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 690, 360);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 710, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitchenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitchenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitchenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitchenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitchenView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextPane OrderJTextPane;
    public javax.swing.JButton ReadyButton;
    public javax.swing.JButton ShowButton;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
