/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nacho
 */
public class BallBoxView extends javax.swing.JFrame {

    /**
     * Creates new form BallBoxView
     */
    public BallBoxView() {
        initComponents();
        setSize(850, 625);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        BallBoxPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CreationComboBox = new javax.swing.JComboBox<>();
        SpeedSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        BallsNumberSpinner = new javax.swing.JSpinner();
        GenerateButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BallBoxPannel.setBackground(new java.awt.Color(0, 0, 0));
        BallBoxPannel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BallBoxPannel.setLayout(null);
        getContentPane().add(BallBoxPannel);
        BallBoxPannel.setBounds(20, 20, 530, 540);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Speed");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 330, 240, 50);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creation Method");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 60, 240, 50);

        CreationComboBox.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        CreationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flyweight", "Prototype", "None" }));
        getContentPane().add(CreationComboBox);
        CreationComboBox.setBounds(580, 110, 190, 50);

        SpeedSpinner.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(SpeedSpinner);
        SpeedSpinner.setBounds(590, 380, 170, 50);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Number of Balls");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 200, 240, 50);

        BallsNumberSpinner.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(BallsNumberSpinner);
        BallsNumberSpinner.setBounds(590, 260, 170, 50);

        GenerateButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        GenerateButton.setText("Generate");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateButton);
        GenerateButton.setBounds(600, 470, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BallBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BallBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BallBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BallBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BallBoxView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BallBoxPannel;
    public javax.swing.JSpinner BallsNumberSpinner;
    public javax.swing.JComboBox<String> CreationComboBox;
    public javax.swing.JButton GenerateButton;
    public javax.swing.JSpinner SpeedSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
